-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 2bd608119f0f1d0783117e1d8a42210d84ca81f3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        - -v
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b7f5d468c67c3c4a6ea7cdf68c40778095b0f19b
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: git://github.com/guykisel/pre-commit-reject-large-files
    sha: 60a7d18671832d36f003525235a8a2a603166644
    hooks:
    -   id: reject-large-files
